// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD536mgYN64Qs2zmyvlKzPlK6LMlNpgUg',
    appId: '1:357658795092:web:60cadb14a4f770c7b121c1',
    messagingSenderId: '357658795092',
    projectId: 'reddit-clone-486f3',
    authDomain: 'reddit-clone-486f3.firebaseapp.com',
    storageBucket: 'reddit-clone-486f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFYqCSILZ4rvaJiEvGVkfWw8hzWfgh43k',
    appId: '1:357658795092:android:6eb1b837a8e6d2cfb121c1',
    messagingSenderId: '357658795092',
    projectId: 'reddit-clone-486f3',
    storageBucket: 'reddit-clone-486f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFcnHyh8vxQDfbVtiXC77dnJGVs8By1r8',
    appId: '1:357658795092:ios:9ee1d55474d1e3d9b121c1',
    messagingSenderId: '357658795092',
    projectId: 'reddit-clone-486f3',
    storageBucket: 'reddit-clone-486f3.firebasestorage.app',
    iosBundleId: 'com.example.flutterRedditClone',
  );
}
